baseURL = "https://xn--ynyo-2nad.com/"
languageCode = "en-us"
title = "yányào.com"
theme = "huglog"

pygmentsstyle = "solarized-dark"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true



[params]
subtitle = "looking a wood sprite in the forest"
favicon = "data:image/svg+xml,<svg xmlns=%22http://www.w3.org/2000/svg%22 viewBox=%220 0 100 100%22><text y=%22.9em%22 font-size=%2290%22>🎯</text></svg>"


[[menu.main]]
name = "Home"
url = "/"
weight = 1

[[menu.main]]
name = "Posts"
url = "/posts"
weight = 2

[[menu.main]]
name = "Tags"
url = "/tags"
weight = 3

[[params.social]]
name = "RSS"
icon = "rss"
url = "/index.xml"

[[params.social]]
name = "Status"
icon = "activity"
url = "/daydayup/"

[[params.social]]
name = "microfeed"
icon = "radio"
url = "https://yankuiyi.com/"

[[params.social]]
name = "Logseq"
icon = "inbox"
url = "https://fouland.com/"


[[params.social]]
name = "Mastodon"
icon = "at-sign"
url = "https://at.yadanhe.com/"
